# Create Patient Queue Entry
mutation CreateQueueEntry(
  $id: String!
  $hospitalId: String!
  $doctorId: String!
  $patientId: String!
  $tokenNumber: String!
) @auth(level: USER) {
  queueEntry_insert(
    data: {
      id: $id
      hospitalId: $hospitalId
      doctorId: $doctorId
      patientId: $patientId
      tokenNumber: $tokenNumber
      status: "Waiting"
    }
  )
}

# Update Queue Entry Status
mutation UpdateQueueStatus($id: String!, $status: String!) @auth(level: USER) {
  queueEntry_update(id: $id, data: { status: $status })
}
